#ifndef NVIC_H
#define NVIC_H

#include "stm32l.h"

#define WWDG_IRQChannel                 ((uint8_t)0x00)
#define PVD_IRQChannel                  ((uint8_t)0x01)
#define TAMPER_IRQChannel               ((uint8_t)0x02)
#define RTC_WKUP_IRQChannel             ((uint8_t)0x03)
#define FLASH_IRQChannel                ((uint8_t)0x04)
#define RCC_IRQChannel                  ((uint8_t)0x05)
#define EXTI0_IRQChannel                ((uint8_t)0x06)
#define EXTI1_IRQChannel                ((uint8_t)0x07)
#define EXTI2_IRQChannel                ((uint8_t)0x08)
#define EXTI3_IRQChannel                ((uint8_t)0x09)
#define EXTI4_IRQChannel                ((uint8_t)0x0a)
#define DMA1_Channel1_IRQChannel        ((uint8_t)0x0b)
#define DMA1_Channel2_IRQChannel        ((uint8_t)0x0c)
#define DMA1_Channel3_IRQChannel        ((uint8_t)0x0d)
#define DMA1_Channel4_IRQChannel        ((uint8_t)0x0e)
#define DMA1_Channel5_IRQChannel        ((uint8_t)0x0f)
#define DMA1_Channel6_IRQChannel        ((uint8_t)0x10)
#define DMA1_Channel7_IRQChannel        ((uint8_t)0x11)
#define ADC1_2_IRQChannel               ((uint8_t)0x12)
#define USB_HP_IRQChannel               ((uint8_t)0x13)
#define USB_LP_IRQChannel               ((uint8_t)0x14)
#define DAC_IRQChannel                  ((uint8_t)0x15)
#define COMP_IRQChannel                 ((uint8_t)0x16)
#define EXTI9_5_IRQChannel              ((uint8_t)0x17)
#define LCD_IRQChannel                  ((uint8_t)0x18)
#define TIM9_IRQChannel                 ((uint8_t)0x19)
#define TIM10_IRQChannel                ((uint8_t)0x1a)
#define TIM11_IRQChannel                ((uint8_t)0x1b)
#define TIM2_IRQChannel                 ((uint8_t)0x1c)
#define TIM3_IRQChannel                 ((uint8_t)0x1d)
#define TIM4_IRQChannel                 ((uint8_t)0x1e)
#define I2C1_EV_IRQChannel              ((uint8_t)0x1f)
#define I2C1_ER_IRQChannel              ((uint8_t)0x20)
#define I2C2_EV_IRQChannel              ((uint8_t)0x21)
#define I2C2_ER_IRQChannel              ((uint8_t)0x22)
#define SPI1_IRQChannel                 ((uint8_t)0x23)
#define SPI2_IRQChannel                 ((uint8_t)0x24)
#define USART1_IRQChannel               ((uint8_t)0x25)
#define USART2_IRQChannel               ((uint8_t)0x26)
#define USART3_IRQChannel               ((uint8_t)0x27)
#define EXTI15_10_IRQChannel            ((uint8_t)0x28)
#define RTCAlarm_IRQChannel             ((uint8_t)0x29)
#define USB_FS_WKUP_IRQChannel          ((uint8_t)0x2a)
#define TIM6_IRQChannel                 ((uint8_t)0x2b)
#define TIM7_IRQChannel                 ((uint8_t)0x2c)

#endif
